modLoader="javafml"
loaderVersion="[36,)"
license="Apache License 2.0"

[[mods]] 
	modId="pregen-protect" 
	version="${version}" 
	displayName="PreGen-Protect"
	description='''Restarts a pregen process when server's RAM is running out'''
	side="SERVER"
	authors="PT400C - Jomcraft Network"
	credits="Developed by Jomcraft Network"

[[dependencies.pregen-protect]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="SERVER"
    
[[dependencies.pregen-protect]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,]"
    ordering="NONE"
    side="SERVER"
    
[[dependencies.pregen-protect]]
    modId="chunkpregen"
    mandatory=true
    versionRange="[V1.16-3.1.1,]"
    ordering="NONE"
    side="SERVER"    